const data = [
    { "NOM_PRENOM_TITULAIRE": "BARON PIERRICK", "NUM_CLIENT": "12854", "NOM_CLIENT": "SEBILEAU CAROLE", "DP_IS": "0", "LIB_COURT_REGIME_IMPOT": "BA-RSO-IR" },
    { "NOM_PRENOM_TITULAIRE": "BARON PIERRICK", "NUM_CLIENT": "4821", "NOM_CLIENT": "EARL HEGRON", "DP_IS": "0", "LIB_COURT_REGIME_IMPOT": "BA-RS-IR" },
    { "NOM_PRENOM_TITULAIRE": "BARON PIERRICK", "NUM_CLIENT": "4667", "NOM_CLIENT": "MOREAU DIDIER", "DP_IS": "0", "LIB_COURT_REGIME_IMPOT": "BA-RN-IR" },
    { "NOM_PRENOM_TITULAIRE": "BARON PIERRICK", "NUM_CLIENT": "5867", "NOM_CLIENT": "EARL MAEL", "DP_IS": "0", "LIB_COURT_REGIME_IMPOT": "BA-RN-IR" },
    { "NOM_PRENOM_TITULAIRE": "BARON PIERRICK", "NUM_CLIENT": "14321", "NOM_CLIENT": "EARL SOFADE", "DP_IS": "0", "LIB_COURT_REGIME_IMPOT": "BA-RN-IR" },
    { "NOM_PRENOM_TITULAIRE": "BARON PIERRICK", "NUM_CLIENT": "5093", "NOM_CLIENT": "EARL GIBIER DE LA CLE DES CHAMPS", "DP_IS": "0", "LIB_COURT_REGIME_IMPOT": "BA-RNO-IR" },
    { "NOM_PRENOM_TITULAIRE": "BARON PIERRICK", "NUM_CLIENT": "6672", "NOM_CLIENT": "ASLI TRINCTIERE", "DP_IS": null, "LIB_COURT_REGIME_IMPOT": "BIC-NF" },
    { "NOM_PRENOM_TITULAIRE": "BARON PIERRICK", "NUM_CLIENT": "5853", "NOM_CLIENT": "PICARD MARCEL", "DP_IS": "0", "LIB_COURT_REGIME_IMPOT": "BA-RN-IR" },
    { "NOM_PRENOM_TITULAIRE": "BARON PIERRICK", "NUM_CLIENT": "22748", "NOM_CLIENT": "MARTIN CHRISTINE", "DP_IS": "0", "LIB_COURT_REGIME_IMPOT": "BA-RS-IR" },
    { "NOM_PRENOM_TITULAIRE": "BARON PIERRICK", "NUM_CLIENT": "6470", "NOM_CLIENT": "CHEVALIER ALEXIA", "DP_IS": "0", "LIB_COURT_REGIME_IMPOT": "BA-RSO-IR" },
    { "NOM_PRENOM_TITULAIRE": "BARON PIERRICK", "NUM_CLIENT": "6912", "NOM_CLIENT": "CHAMPAIN JEAN-CLAUDE", "DP_IS": "0", "LIB_COURT_REGIME_IMPOT": "BA-RS-IR" },
    { "NOM_PRENOM_TITULAIRE": "BARON PIERRICK", "NUM_CLIENT": "7048", "NOM_CLIENT": "EARL MAINELO", "DP_IS": "0", "LIB_COURT_REGIME_IMPOT": "BA-RN-IR" }]

export default data;