version: '3.8'
services:
  client:
    stdin_open: true
    image: react-vite-dev:1.0
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - "/app/node_modules"
      - "./:/app"
